### ISSUE TITLE
Some services fail to start

### ISSUE THREAD

**Issue by bahaisi** [twosixlabs-dart/kafka-examples-docker#5]
When I run:

```
docker-compose -f python.yml pull
docker-compose -f python.yml up -d
```

The following services immediately exit with status 1:
- twosixlabsdart/python-kafka-producer:latest
- twosixlabsdart/python-kafka-consumer:latest
- twosixlabsdart/python-kafka-streams:latest

Here are the logs:
```
#twosixlabsdart/python-kafka-producer:latest

+ƒaµS† v1.10.4+------------------------------------------+
| id          | pyproducer                               |
| transport   | [URL('kafka://kafka-broker-1:19092')]    |
| store       | memory:                                  |
| web         | http://localhost:6066/                   |
| log         | -stderr- (info)                          |
| pid         | 1                                        |
| hostname    | 54ec6fa1cd0a                             |
| platform    | CPython 3.6.8 (Linux x86_64)             |
| drivers     |                                          |
|   transport | aiokafka=1.1.6                           |
|   web       | aiohttp=3.6.2                            |
| datadir     | /pyproducer-data                         |
| appdir      | /pyproducer-data/v1                      |
+-------------+------------------------------------------+
[2020-06-18 13:23:57,402] [1] [INFO] [^Worker]: Starting... 
[2020-06-18 13:23:57,408] [1] [INFO] [^-App]: Starting... 
[2020-06-18 13:23:57,408] [1] [INFO] [^--Monitor]: Starting... 
[2020-06-18 13:23:57,408] [1] [INFO] [^--Producer]: Starting... 
[2020-06-18 13:23:57,408] [1] [INFO] [^---ProducerBuffer]: Starting... 
[2020-06-18 13:23:57,415] [1] [ERROR] Unable connect to "kafka-broker-1:19092": [Errno 111] Connect call failed ('172.20.0.3', 19092) 
[2020-06-18 13:23:57,422] [1] [ERROR] [^Worker]: Error: ConnectionError("Unable to bootstrap from [('kafka-broker-1', 19092, <AddressFamily.AF_UNSPEC: 0>)]",) 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mode/worker.py", line 273, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
    await self.on_start()
  File "/usr/local/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 1021, in on_start
    await producer.start()
  File "/usr/local/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 178, in start
    await self.client.bootstrap()
  File "/usr/local/lib/python3.6/site-packages/aiokafka/client.py", line 231, in bootstrap
    'Unable to bootstrap from {}'.format(self.hosts))
kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('kafka-broker-1', 19092, <AddressFamily.AF_UNSPEC: 0>)]
[2020-06-18 13:23:57,425] [1] [INFO] [^Worker]: Stopping... 
[2020-06-18 13:23:57,426] [1] [INFO] [^-App]: Stopping... 
[2020-06-18 13:23:57,426] [1] [INFO] [^-App]: Flush producer buffer... 
[2020-06-18 13:23:57,427] [1] [INFO] [^--TableManager]: Stopping... 
[2020-06-18 13:23:57,428] [1] [INFO] [^---Fetcher]: Stopping... 
[2020-06-18 13:23:57,428] [1] [INFO] [^---Conductor]: Stopping... 
[2020-06-18 13:23:57,429] [1] [INFO] [^--AgentManager]: Stopping... 
[2020-06-18 13:23:57,429] [1] [INFO] [^--ReplyConsumer]: Stopping... 
[2020-06-18 13:23:57,430] [1] [INFO] [^--LeaderAssignor]: Stopping... 
[2020-06-18 13:23:57,430] [1] [INFO] [^--Consumer]: Stopping... 
[2020-06-18 13:23:57,431] [1] [INFO] [^--Web]: Stopping... 
[2020-06-18 13:23:57,431] [1] [INFO] [^--CacheBackend]: Stopping... 
[2020-06-18 13:23:57,432] [1] [INFO] [^--Producer]: Stopping... 
[2020-06-18 13:23:57,432] [1] [INFO] [^---ProducerBuffer]: Stopping... 
[2020-06-18 13:23:57,433] [1] [INFO] [^--Monitor]: Stopping... 
[2020-06-18 13:23:57,434] [1] [INFO] [^Worker]: Gathering service tasks... 
[2020-06-18 13:23:57,435] [1] [INFO] [^Worker]: Gathering all futures... 
[2020-06-18 13:23:59,442] [1] [INFO] [^Worker]: Closing event loop 
```

```
#twosixlabsdart/python-kafka-consumer:latest
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/importlib_resources/_py3.py", line 85, in open_binary
    return open(full_path, mode='rb')
FileNotFoundError: [Errno 2] No such file or directory: '/pyconsumer/resources/env/compose.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/pyconsumer/__init__.py", line 18, in <module>
    config_loader.read_text('pyconsumer.resources.env', config_name)
  File "/usr/local/lib/python3.6/site-packages/importlib_resources/_py3.py", line 131, in read_text
    with open_text(package, resource, encoding, errors) as fp:
  File "/usr/local/lib/python3.6/site-packages/importlib_resources/_py3.py", line 109, in open_text
    open_binary(package, resource), encoding=encoding, errors=errors)
  File "/usr/local/lib/python3.6/site-packages/importlib_resources/_py3.py", line 99, in open_binary
    raise FileNotFoundError(message)
FileNotFoundError: 'compose.json' resource not found in 'pyconsumer.resources.env'
```

```
#twosixlabsdart/python-kafka-streams:latest
+ƒaµS† v1.10.4+------------------------------------------+
| id          | pystreams                                |
| transport   | [URL('kafka://kafka-broker-1:19092')]    |
| store       | memory:                                  |
| web         | http://localhost:6066/                   |
| log         | -stderr- (info)                          |
| pid         | 1                                        |
| hostname    | 7363eb9217f4                             |
| platform    | CPython 3.6.8 (Linux x86_64)             |
| drivers     |                                          |
|   transport | aiokafka=1.1.6                           |
|   web       | aiohttp=3.6.2                            |
| datadir     | /pystreams-data                          |
| appdir      | /pystreams-data/v1                       |
+-------------+------------------------------------------+
[2020-06-18 13:23:57,531] [1] [INFO] [^Worker]: Starting... 
[2020-06-18 13:23:57,536] [1] [INFO] [^-App]: Starting... 
[2020-06-18 13:23:57,537] [1] [INFO] [^--Monitor]: Starting... 
[2020-06-18 13:23:57,537] [1] [INFO] [^--Producer]: Starting... 
[2020-06-18 13:23:57,537] [1] [INFO] [^---ProducerBuffer]: Starting... 
[2020-06-18 13:23:57,542] [1] [ERROR] Unable connect to "kafka-broker-1:19092": [Errno 111] Connect call failed ('172.20.0.3', 19092) 
[2020-06-18 13:23:57,546] [1] [ERROR] [^Worker]: Error: ConnectionError("Unable to bootstrap from [('kafka-broker-1', 19092, <AddressFamily.AF_UNSPEC: 0>)]",) 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mode/worker.py", line 273, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
    await self.on_start()
  File "/usr/local/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 1021, in on_start
    await producer.start()
  File "/usr/local/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 178, in start
    await self.client.bootstrap()
  File "/usr/local/lib/python3.6/site-packages/aiokafka/client.py", line 231, in bootstrap
    'Unable to bootstrap from {}'.format(self.hosts))
kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('kafka-broker-1', 19092, <AddressFamily.AF_UNSPEC: 0>)]
[2020-06-18 13:23:57,549] [1] [INFO] [^Worker]: Stopping... 
[2020-06-18 13:23:57,550] [1] [INFO] [^-App]: Stopping... 
[2020-06-18 13:23:57,550] [1] [INFO] [^-App]: Flush producer buffer... 
[2020-06-18 13:23:57,550] [1] [INFO] [^--TableManager]: Stopping... 
[2020-06-18 13:23:57,551] [1] [INFO] [^---Fetcher]: Stopping... 
[2020-06-18 13:23:57,551] [1] [INFO] [^---Conductor]: Stopping... 
[2020-06-18 13:23:57,552] [1] [INFO] [^--AgentManager]: Stopping... 
[2020-06-18 13:23:57,552] [1] [INFO] [^Agent: pystreams.streams.ag[.]stream_in]: Stopping... 
[2020-06-18 13:23:57,553] [1] [INFO] [^--ReplyConsumer]: Stopping... 
[2020-06-18 13:23:57,553] [1] [INFO] [^--LeaderAssignor]: Stopping... 
[2020-06-18 13:23:57,554] [1] [INFO] [^--Consumer]: Stopping... 
[2020-06-18 13:23:57,554] [1] [INFO] [^--Web]: Stopping... 
[2020-06-18 13:23:57,555] [1] [INFO] [^--CacheBackend]: Stopping... 
[2020-06-18 13:23:57,555] [1] [INFO] [^--Producer]: Stopping... 
[2020-06-18 13:23:57,556] [1] [INFO] [^---ProducerBuffer]: Stopping... 
[2020-06-18 13:23:57,557] [1] [INFO] [^--Monitor]: Stopping... 
[2020-06-18 13:23:57,557] [1] [INFO] [^Worker]: Gathering service tasks... 
[2020-06-18 13:23:57,558] [1] [INFO] [^Worker]: Gathering all futures... 
[2020-06-18 13:23:59,565] [1] [INFO] [^Worker]: Closing event loop 
```

**Comment by Lnk2past** [comment]
Outside of configuration issues within the individual components (producer, stream-processor, consumer), the problem is with docker-compose and the speed at which services are being launched. I have fixed all of the configuration issues and released new Docker images for each of these components. Make sure to pull the new images.

So while those three components properly depend on the topic-provisioner and the kafka broker (in python.yml), Docker is only looking at when those containers are successfully started, not when the services running within are successfully completed. Thus, the three components are failing to connect to the Kafka broker because it does not "exist" yet.

Therefore, you should run the following:

```
docker-compose -f python.yml pull
docker-compose -f python.yml up -d
# ... wait a few seconds for the three components to fail and for Kafka to come "online"
docker-compose -f python.yml up -d
```

Feel free to omit the `-d` flag on the second run through to see all output from the docker containers. Eventually you'll see messages that look like:

```
consumer_1                | [2020-06-18 18:07:31,055] [1] [WARNING] persisting 5d88aaa4-fd01-4207-b27a-1acf64e2c3db
```

Please let me know if any other problems persist

**Comment by bahaisi** [comment]
@Lnk2past thanks!
